# NLP

In [1]:
!pip install transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.4/7.4 MB 15.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 25.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 36.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 42.8 MB/s eta 0:00:00


In [2]:
import transformers

In [3]:
!pip install transformers[sentencepiece]

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 6.7 MB/s eta 0:00:00


In [4]:
from transformers import pipeline

In [ ]:
classifier = pipeline("sentiment-analysis", model='ProsusAI/finbert')
classifier("I've been waiting for a HuggingFace course my whole life.")

No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
Xformers is not installed correctly. If you want to use memory_efficient_attention to accelerate training use the following command to install Xformers
pip install xformers.


[{'label': 'neutral', 'score': 0.9240476489067078}]

In [ ]:
classifier("Its raining today since morning.")

[{'label': 'neutral', 'score': 0.5516395568847656}]

In [ ]:
classifier("Its raining today since morning and I have to go out to meet somone")

[{'label': 'negative', 'score': 0.6042881011962891}]

In [ ]:
classifier("Its a sunny day so iI can play cricket with my friends after a long time.")

[{'label': 'neutral', 'score': 0.8840293884277344}]

In [ ]:
classifier("i scored well in my exams.")

[{'label': 'positive', 'score': 0.9272652268409729}]

In [ ]:
generator = pipeline('text-generation', model="gpt2")
generator("Its August month, and I live in Pune India. Likelihood of raining today is")

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py:1369: UserWarning: Using `max_length`'s default (50) to control the generation length. This behaviour is deprecated and will be removed from the config in v5 of Transformers -- we recommend using `max_new_tokens` to control the maximum length of the generation.
  warnings.warn(


[{'generated_text': 'Its August month, and I live in Pune India. Likelihood of raining today is zero. Not just in the north east or South and Southeast or even Western India.\n\nIn many cases, the entire country will be affected by this weather'}]

In [ ]:
generator("machine learning is a growing research field which could ")

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


[{'generated_text': 'machine learning is a growing research field which could ersatz the basic idea behind "learning in a language."\n\n\nA group of four scientists with recently published work on learning in Chinese has taken a new approach — from learning languages using Python,'}]

In [ ]:
generator = pipeline("text-generation", model="distilgpt2")
generator(
    "In this course, we will teach you how to",
    max_length=30,
    num_return_sequences=2,
)

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


[{'generated_text': 'In this course, we will teach you how to use SQL, including new tools like CRISPR and Ruby2 to query your DB using Ruby2'},
 {'generated_text': 'In this course, we will teach you how to get your hands on a controller and how to use the controller to perform an amazing event.'}]

In [5]:
import tensorflow as tf

In [6]:
classifier = pipeline('sentiment-analysis')
classifier(
    [
        "Its a rainy and a gloomy day today.",
        "The football club which I support, won last night."
    ]
)

No model was supplied, defaulted to distilbert-base-uncased-finetuned-sst-2-english and revision af0f99b (https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.


No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
Xformers is not installed correctly. If you want to use memory_efficient_attention to accelerate training use the following command to install Xformers
pip install xformers.


[{'label': 'NEGATIVE', 'score': 0.9917491674423218},
 {'label': 'POSITIVE', 'score': 0.9991034865379333}]

In [7]:
from transformers import AutoTokenizer

In [8]:
checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

In [10]:
raw_inputs = [
    "Its a rainy and a gloomy day today.",
        "The football club which I support, won last night."
]

inputs = tokenizer(raw_inputs, padding=True, truncation=True, return_tensors='tf')
print(inputs)

{'input_ids': <tf.Tensor: shape=(2, 13), dtype=int32, numpy=
array([[  101,  2049,  1037, 16373,  1998,  1037, 24067,  2100,  2154,
         2651,  1012,   102,     0],
       [  101,  1996,  2374,  2252,  2029,  1045,  2490,  1010,  2180,
         2197,  2305,  1012,   102]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(2, 13), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}


In [11]:
from transformers import TFAutoModel

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
model = TFAutoModel.from_pretrained(checkpoint)

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFDistilBertModel: ['classifier.weight', 'pre_classifier.weight', 'classifier.bias', 'pre_classifier.bias']
- This IS expected if you are initializing TFDistilBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFDistilBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertModel for predictions without further training.


In [12]:
outputs = model(inputs)
print(outputs)

TFBaseModelOutput(last_hidden_state=<tf.Tensor: shape=(2, 13, 768), dtype=float32, numpy=
array([[[-0.57946014,  0.36661053, -0.23057458, ..., -0.2240211 ,
          0.05542259,  0.22230959],
        [-0.9477185 ,  0.35537142, -0.08677168, ..., -0.36991656,
          0.20979163,  0.39808896],
        [-1.0169145 ,  0.5024735 , -0.25274485, ..., -0.15454277,
         -0.15448332,  0.43136212],
        ...,
        [-0.00722921,  0.2233052 , -0.41761628, ..., -0.03856578,
         -0.19325414, -0.19303681],
        [ 0.28191215,  0.41949353, -0.18460724, ..., -0.04427713,
         -0.24997486, -0.06197189],
        [-0.53053784,  0.4397316 , -0.01007073, ..., -0.02397217,
          0.09924489,  0.19551836]],

       [[ 0.25360873,  0.0220342 ,  0.39595225, ...,  0.16799128,
          0.48274076, -0.2549588 ],
        [ 0.4408057 ,  0.1012353 ,  0.15190187, ...,  0.157918  ,
          0.65337616, -0.35781366],
        [ 0.07628267,  0.32859203,  0.33957955, ..., -0.03510229,
          0.4

In [17]:
print(outputs.last_hidden_state.shape)

(2, 13, 768)


In [18]:
from transformers import TFAutoModelForSequenceClassification

model = TFAutoModelForSequenceClassification.from_pretrained(checkpoint)
outputs = model(inputs)

All PyTorch model weights were used when initializing TFDistilBertForSequenceClassification.

All the weights of TFDistilBertForSequenceClassification were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertForSequenceClassification for predictions without further training.


In [19]:
print(outputs.logits.shape)

(2, 2)


In [21]:
print(outputs.logits)

tf.Tensor(
[[ 2.5818617 -2.2072885]
 [-3.4306655  3.5854695]], shape=(2, 2), dtype=float32)


In [23]:
predictions = tf.math.softmax(outputs.logits, axis=-1)
print(predictions)

tf.Tensor(
[[9.9174917e-01 8.2508810e-03]
 [8.9648220e-04 9.9910349e-01]], shape=(2, 2), dtype=float32)


In [25]:
model.config.id2label

{0: 'NEGATIVE', 1: 'POSITIVE'}